export {default as Home} from './Home'
export {default as NavBar} from './NavBar'
export {default as Men} from './Men'
export {default as PicUpload} from './PicUpload'
export {default as Women} from './Women'
export {default as Contact} from './Contact'
export {default as Admin} from './Admin'